### ISSUE TITLE
Make the Helm Chart available

### ISSUE THREAD

**Issue by hhoover** [boozallen/sdp-pipeline-framework#2]
Documentation refers to a Helm chart repository that is not open source (or at least, is not viewable) 

https://github.com/boozallen/sdp-helm-chart

**Comment by boydj** [comment]
It's coming! We are working through removing some firm specific configuration from the charts
________________________________

**Comment by kottoson** [comment]
The Helm chart repository should be available now. Happy Helming!

https://github.com/boozallen/sdp-helm-chart
